### ISSUE TITLE
Saving HTML causes ascii codec errors in some environments

### ISSUE THREAD

**Issue by andrewnags** [andrewnags/uOcourses#13]
Sample traceback
```
Traceback (most recent call last):
  File "/usr/local/bin/uoapi", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/uoapi/cli_tools.py", line 34, in cli
    return function(args)
  File "/usr/local/lib/python3.6/dist-packages/uoapi/cli.py", line 59, in cli
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/uoapi/cli_tools.py", line 34, in cli
    return function(args)
  File "/usr/local/lib/python3.6/dist-packages/uoapi/timetable/cli.py", line 105, in cli
    args.saveraw, args.refresh, args.retries, args.waittime,
  File "/usr/local/lib/python3.6/dist-packages/uoapi/timetable/cli.py", line 136, in main
    f.write(resp)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 123242: ordinal not in range(128)
```
Query: 2020 Winter ADM1
Python: 3.6.9
System: Linux <private> 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Same error generated in downstream logging of this issue.

Suggested hotfix: Make HTML-saving best-effort.  Catch exceptions and disregard.

Permanent fix requires further investigationg.

Start of super-long log-failure message:
```
UnicodeEncodeError('ascii', '<?xml version=\'1.0\' encoding=\'utf-8\' ?>\n<PAGE id=\'UO_PUB_CLSSRCH_RES\'><GENSCRIPT id=\'script\'><![CDATA[var oWin=window;\n var oDoc = window.document;\noWin.strCurrUrl=\'https://uocampus.public.uottawa.ca/psc/csprpr9pub/EMPLOYEE/SA/c/UO_SR_AA_MODS.UO_PUB_CLSSRCH.GBL?&PAGE=UO_PUB_CLSSRCH_RES\';\noWin.strReqURL=\'\';\n]]></
```
End:
```
A = false;\nbAccessibleLayout = false;\nbGenDomInfo = false;\n]]></SYSVAR></PAGE>', 123242, 123243, 'ordinal not in range(128)')
```

**Comment by andrewnags** [comment]
Solved by specifying `encoding="utf-8"` when opening the file to write the html to disk.

Thanks @taliamax!
